---
title: "GroupProj"
author: "Ashley Steinkrauss"
date: "2024-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##load in any needed packages
```{r}
library(tidyverse)
library(ggplot2)
library(devtools)
library(tidyr)
library(dplyr)
library(knitr)
library(plotly) #interactive graphs

#install.packages("usmap")
library(usmap)
library(scales)
```

#load in all csv's
```{r}
#experiment_txt <- read.csv(file.choose(), header = T) #Select csv file, will open your computer and you can select your files
Fruit2013 = read.csv("/Users/ashleysteinkrauss/Desktop/7900/GroupProj/Fruit Prices 2013.csv") #edit these to match your directory path
Fruit2013 = Fruit2013[, 1:9] #grabbing first 9 columns, some excels had empty slots that were being read in weird
Fruit2016 = read.csv("/Users/ashleysteinkrauss/Desktop/7900/GroupProj/Fruit Prices 2016.csv")
Fruit2016 = Fruit2016[, 1:9]
Fruit2020 = read.csv("/Users/ashleysteinkrauss/Desktop/7900/GroupProj/Fruit Prices 2020.csv")
Fruit2020 = Fruit2020[, 1:9]

Veg2013 = read.csv("/Users/ashleysteinkrauss/Desktop/7900/GroupProj/Vegetable Prices 2013.csv")
Veg2013 = Veg2013[, 1:9]
Veg2016 = read.csv("/Users/ashleysteinkrauss/Desktop/7900/GroupProj/Vegetable Prices 2016.csv")
Veg2016 = Veg2016[, 1:9]
Veg2020 = read.csv("/Users/ashleysteinkrauss/Desktop/7900/GroupProj/Vegetable Prices 2020.csv")
Veg2020 = Veg2020[, 1:9]


Income = read.csv("/Users/ashleysteinkrauss/Desktop/7900/GroupProj/Annual person income by county.csv")
```

#format data to make year long format
```{r}
Fruits = rbind(Fruit2013, Fruit2016, Fruit2020) #make long by combining all repeated columns
Veggies = rbind(Veg2013, Veg2016, Veg2020)

AnnualIncome <- pivot_longer(Income, cols = c("X2013", "X2016", "X2020"), names_to = "Year", values_to = "Value") #make 3 year columns into one
```

#questions of interest

#1. prices changed by type and overall of fruits and veggies by year (nothing related to income)
```{r}
# For fruits
fruit_prices <- aggregate(CupEquivalentPrice ~ Fruit + Year + Form, data = Fruits, FUN = mean)

# For veggies
veggie_prices <- aggregate(CupEquivalentPrice ~ Vegetable + Year + Form, data = Veggies, FUN = mean)

# Plotting
# Convert Year to factor with specific levels
fruit_prices$Year <- factor(fruit_prices$Year, levels = c("2013", "2016", "2020"))
veggie_prices$Year <- factor(veggie_prices$Year, levels = c("2013", "2016", "2020"))

#make tables
# For fruits
fruit_summary <- Fruits %>%
  group_by(Year) %>%
  summarise(mean_price = mean(CupEquivalentPrice),
            median_price = median(CupEquivalentPrice),
            min_price = min(CupEquivalentPrice),
            max_price = max(CupEquivalentPrice))

# For veggies
veggie_summary <- Veggies %>%
  group_by(Year) %>%
  summarise(mean_price = mean(CupEquivalentPrice),
            median_price = median(CupEquivalentPrice),
            min_price = min(CupEquivalentPrice),
            max_price = max(CupEquivalentPrice))

# View the summaries
cat("Fruit Summary:\n")
kable(fruit_summary, align = "c")

cat("\nVeggie Summary:\n")
kable(veggie_summary, align = "c")


# Plot the graph with a legend
ggplot(fruit_prices, aes(x = Year, y = CupEquivalentPrice, group = Fruit, color = Fruit)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Price per edible cup equivalent ", title = "Average Price per Edible Cup Equivalent of Fruits by Year", color = "Fruit Type") +
  theme_minimal() +
  theme(legend.position = "right")

ggplot(veggie_prices, aes(x = Year, y = CupEquivalentPrice, group = Vegetable, color = Vegetable)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Price per edible cup equivalent ", title = "Average Price per Edible Cup Equivalent of Vegetables by Year", color = "Vegetable Type") +
  theme_minimal() +
  theme(legend.position = "right")

#or 

# Convert ggplot graph to interactive plotly graph
interactive_plot_fruit <- ggplotly(ggplot(fruit_prices, aes(x = Year, y = CupEquivalentPrice, group = Fruit, color = Fruit)) +
                                geom_line() +
                                geom_point() +
                                labs(x = "Year", y = "Price per edible cup equivalent", title = "Average Price per Edible Cup Equivalent of Fruits by Year", color = "Fruit Type") +
                                theme_minimal() +
                                theme(legend.position = "right"))

# Display the interactive plot
interactive_plot_fruit

# Convert ggplot graph to interactive plotly graph
interactive_plot_veggie <- ggplotly(ggplot(veggie_prices, aes(x = Year, y = CupEquivalentPrice, group = Vegetable, color = Vegetable)) +
                                geom_line() +
                                geom_point() +
                                labs(x = "Year", y = "Price per edible cup equivalent", title = "Average Price per Edible Cup Equivalent of Vegetables by Year", color = "Vegetable Type") +
                                theme_minimal() +
                                theme(legend.position = "right"))

# Display the interactive plot
interactive_plot_veggie
```


2. Prices visualization of income by state/county by year:
```{r}
#probably need to change $$$ value to a more readable number 
# For personal income by capita
income_by_capita <- subset(AnnualIncome, Description == "Per capita personal income (dollars) 2/")

# Rename X2016 to 2016 and X2020 to 2020 in the Year column
income_by_capita <- income_by_capita %>% 
  mutate(Year = ifelse(Year == "X2013", "2013", 
                ifelse(Year == "X2016", "2016",
                ifelse(Year == "X2020", "2020", Year))))
# Convert Year column to numeric
income_by_capita$Year <- as.numeric(income_by_capita$Year)

# Convert the Value column to numeric (if needed)
income_by_capita$Value <- as.numeric(income_by_capita$Value)


# Aggregate data by year and state
agg_income <- aggregate(Value ~ Year + GeoFIPS + GeoName, data = income_by_capita, FUN = mean)
# Format the Value column in personal_income
#agg_income$Value <- comma(agg_income$Value)

# Filter data for each year
income_2013 <- agg_income[agg_income$Year == 2013, ]
income_2016 <- agg_income[agg_income$Year == 2016, ]
income_2020 <- agg_income[agg_income$Year == 2020, ]

# Generate the maps for each year
# Get US state boundaries data
us_states <- us_map(regions = "states")

#all years
# Merge using state abbreviations in us_states and FIPS codes in agg_income
map_income <- merge(us_states, agg_income, by.x = "full", by.y = "GeoName")
# Create a plot with ggplot
g <- ggplot(map_income) +
  geom_sf(aes(fill = Value)) +
  scale_fill_distiller(name = "Income", palette = "Spectral") +
  ggtitle("Personal Income by State")
g
# Convert ggplot to plotly object
plotly_g <- ggplotly(g)
# Display the interactive plot
plotly_g

#2013
# Merge using state abbreviations in us_states and FIPS codes in agg_income
map_income_2013 <- merge(us_states, income_2013, by.x = "full", by.y = "GeoName")
# Create a plot with ggplot
g_2013 <- ggplot(map_income_2013) +
  geom_sf(aes(fill = Value)) +
  scale_fill_distiller(name = "Income", palette = "Spectral") +
  ggtitle("Personal Income by State in 2013")
g_2013
# Convert ggplot to plotly object
plotly_g_2013 <- ggplotly(g_2013)
# Display the interactive plot
plotly_g_2013

#2016
# Merge using state abbreviations in us_states and FIPS codes in agg_income
map_income_2016 <- merge(us_states, income_2016, by.x = "full", by.y = "GeoName")
# Create a plot with ggplot
g_2016 <- ggplot(map_income_2016) +
  geom_sf(aes(fill = Value)) +
  scale_fill_distiller(name = "Income", palette = "Spectral") +
  ggtitle("Personal Income by State in 2016")
g_2016
# Convert ggplot to plotly object
plotly_g_2016 <- ggplotly(g_2016)
# Display the interactive plot
plotly_g_2016

#2020
# Merge using state abbreviations in us_states and FIPS codes in agg_income
map_income_2020 <- merge(us_states, income_2020, by.x = "full", by.y = "GeoName")
# Create a plot with ggplot
g_2020 <- ggplot(map_income_2020) +
  geom_sf(aes(fill = Value)) +
  scale_fill_distiller(name = "Income", palette = "Spectral") +
  ggtitle("Personal Income by State in 2020")
g_2020
# Convert ggplot to plotly object
plotly_g_2020 <- ggplotly(g_2020)
# Display the interactive plot
plotly_g_2020
```

# fruit/veggies & form price changes by year:
```{r}
#hard code years
Fruits$Year <- factor(Fruits$Year, levels = c("2013", "2016", "2020"))
Veggies$Year <- factor(Veggies$Year, levels = c("2013", "2016", "2020"))

# Aggregate data by Year and Form to get average CupEquivalentPrice
avg_prices_fruit <- aggregate(CupEquivalentPrice ~ Year + Form + Fruit, data = Fruits, FUN = mean)
avg_prices_veg <- aggregate(CupEquivalentPrice ~ Year + Form + Vegetable, data = Veggies, FUN = mean)


#make tables
# For fruits
fruit_summary_form <- Fruits %>%
  group_by(Year, Form) %>%
  summarise(mean_price = mean(CupEquivalentPrice),
            median_price = median(CupEquivalentPrice),
            min_price = min(CupEquivalentPrice),
            max_price = max(CupEquivalentPrice))

# For veggies
veggie_summary_form <- Veggies %>%
  group_by(Year, Form) %>%
  summarise(mean_price = mean(CupEquivalentPrice),
            median_price = median(CupEquivalentPrice),
            min_price = min(CupEquivalentPrice),
            max_price = max(CupEquivalentPrice))

# View the summaries
cat("Fruit Summary:\n")
kable(fruit_summary_form, align = "c")

cat("\nVeggie Summary:\n")
kable(veggie_summary_form, align = "c")

# Plotting
# Convert ggplot graph to interactive plotly graph
interactive_plot_fruit_form <- ggplotly(ggplot(avg_prices_fuit, aes(x = Year, y = CupEquivalentPrice, group = Fruit, color = Form)) +
                                geom_line() +
                                geom_point() +
                                labs(x = "Year", y = "Cup Equivalent Price", title = "Average Cup Equivalent Price of Fruits by Form Over Years", color = "Fruit Form") +
                                theme_minimal() +
                                theme(legend.position = "right"))

# Display the interactive plot
interactive_plot_fruit_form

# Convert ggplot graph to interactive plotly graph
interactive_plot_veggie_form <- ggplotly(ggplot(avg_prices_veg, aes(x = Year, y = CupEquivalentPrice, group = Vegetable, color = Form)) +
                                geom_line() +
                                geom_point() +
                                labs(x = "Year", y = "Cup Equivalent Price", title = "Average Cup Equivalent Price of Fruits by Form Over Years", color = "Fruit Form") +
                                theme_minimal() +
                                theme(legend.position = "right"))

# Display the interactive plot
interactive_plot_veggie_form
```

#4% of income allocated to fruits & veggies 
#https://money.usnews.com/money/personal-finance/saving-and-budgeting/articles/how-much-should-i-spend-on-groceries
#https://www.nidirect.gov.uk/articles/fruit-and-vegetables

```{r}
#getting 4% and 2% of income 
income_by_capita$four_percent <- income_by_capita$Value * 0.4

income_by_capita$two_percent =  income_by_capita$Value * 0.02


# Adjust CupEquivalentPrice by multiplying by 365
fruit_prices$CupEquivalentPrice_yearly <- fruit_prices$CupEquivalentPrice * 365
veggie_prices$CupEquivalentPrice_yearly <- veggie_prices$CupEquivalentPrice * 365

# Merge income_by_capita with fruit_prices and veggie_prices for each year
merged_fruits_2013 <- merge(subset(income_by_capita, Year == 2013), subset(fruit_prices, Year == 2013), by = "Year")
merged_fruits_2016 <- merge(subset(income_by_capita, Year == 2016), subset(fruit_prices, Year == 2016), by = "Year")
merged_fruits_2020 <- merge(subset(income_by_capita, Year == 2020), subset(fruit_prices, Year == 2020), by = "Year")

merged_veggies_2013 <- merge(subset(income_by_capita, Year == 2013), subset(veggie_prices, Year == 2013), by = "Year")
merged_veggies_2016 <- merge(subset(income_by_capita, Year == 2016), subset(veggie_prices, Year == 2016), by = "Year")
merged_veggies_2020 <- merge(subset(income_by_capita, Year == 2020), subset(veggie_prices, Year == 2020), by = "Year")

# Update meetreq column based on the condition
merged_fruits_2013$meetreq <- ifelse(merged_fruits_2013$two_percent > merged_fruits_2013$CupEquivalentPrice_yearly, "yes", "no")
merged_fruits_2016$meetreq <- ifelse(merged_fruits_2016$two_percent > merged_fruits_2016$CupEquivalentPrice_yearly, "yes", "no")
merged_fruits_2020$meetreq <- ifelse(merged_fruits_2020$two_percent > merged_fruits_2020$CupEquivalentPrice_yearly, "yes", "no")

merged_veggies_2013$meetreq <- ifelse(merged_veggies_2013$two_percent > merged_veggies_2013$CupEquivalentPrice_yearly, "yes", "no")
merged_veggies_2016$meetreq <- ifelse(merged_veggies_2016$two_percent > merged_veggies_2016$CupEquivalentPrice_yearly, "yes", "no")
merged_veggies_2020$meetreq <- ifelse(merged_veggies_2020$two_percent > merged_veggies_2020$CupEquivalentPrice_yearly, "yes", "no")

# Create comparison data frames for each year and each category
comparison_fruits_2013 <- data.frame(Year = merged_fruits_2013$Year,
                                     meetreq = merged_fruits_2013$meetreq,
                                     form = merged_fruits_2013$Form,
                                     CupEquivalentPrice_yearly = merged_fruits_2013$CupEquivalentPrice_yearly)

comparison_fruits_2016 <- data.frame(Year = merged_fruits_2016$Year,
                                     meetreq = merged_fruits_2016$meetreq,
                                     form = merged_fruits_2016$Form,
                                     CupEquivalentPrice_yearly = merged_fruits_2016$CupEquivalentPrice_yearly)

comparison_fruits_2020 <- data.frame(Year = merged_fruits_2020$Year,
                                     meetreq = merged_fruits_2020$meetreq,
                                     form = merged_fruits_2020$Form,
                                     CupEquivalentPrice_yearly = merged_fruits_2020$CupEquivalentPrice_yearly)

comparison_veggies_2013 <- data.frame(Year = merged_veggies_2013$Year,
                                      meetreq = merged_veggies_2013$meetreq,
                                      form = merged_veggies_2013$Form,
                                      CupEquivalentPrice_yearly = merged_veggies_2013$CupEquivalentPrice_yearly)

comparison_veggies_2016 <- data.frame(Year = merged_veggies_2016$Year,
                                      meetreq = merged_veggies_2016$meetreq,
                                      form = merged_veggies_2016$Form,
                                      CupEquivalentPrice_yearly = merged_veggies_2016$CupEquivalentPrice_yearly)

comparison_veggies_2020 <- data.frame(Year = merged_veggies_2020$Year,
                                      meetreq = merged_veggies_2020$meetreq,
                                      form = merged_veggies_2020$Form,
                                      CupEquivalentPrice_yearly = merged_veggies_2020$CupEquivalentPrice_yearly)


# Combine comparison data frames for fruits and veggies across different years
all_comparison_fruits <- rbind(comparison_fruits_2013, comparison_fruits_2016, comparison_fruits_2020)
all_comparison_veggies <- rbind(comparison_veggies_2013, comparison_veggies_2016, comparison_veggies_2020)

# Create tables for fruits and veggies
table_fruits <- table(all_comparison_fruits$meetreq, all_comparison_fruits$Year)
table_veggies <- table(all_comparison_veggies$meetreq, all_comparison_veggies$Year)

# View tables
print("Fruits:")
print(table_fruits)
print("Veggies:")
print(table_veggies)

```

#by form 
```{r}

# Create tables for fruits by form
table_fruits_form_2013 <- table(comparison_fruits_2013$meetreq, comparison_fruits_2013$form)
table_fruits_form_2016 <- table(comparison_fruits_2016$meetreq, comparison_fruits_2016$form)
table_fruits_form_2020 <- table(comparison_fruits_2020$meetreq, comparison_fruits_2020$form)

# Create tables for veggies by form
table_veggies_form_2013 <- table(comparison_veggies_2013$meetreq, comparison_veggies_2013$form)
table_veggies_form_2016 <- table(comparison_veggies_2016$meetreq, comparison_veggies_2016$form)
table_veggies_form_2020 <- table(comparison_veggies_2020$meetreq, comparison_veggies_2020$form)

# View tables
print("Fruits Summary by Form for 2013:")
print(table_fruits_form_2013)
print("Fruits Summary by Form for 2016:")
print(table_fruits_form_2016)
print("Fruits Summary by Form for 2020:")
print(table_fruits_form_2020)

print("Veggies Summary by Form for 2013:")
print(table_veggies_form_2013)
print("Veggies Summary by Form for 2016:")
print(table_veggies_form_2016)
print("Veggies Summary by Form for 2020:")
print(table_veggies_form_2020)

```
#prop of yes/no
```{r}
# Calculate proportions for fruits in 2013
table_fruits_form_2013_prop <- table_fruits_form_2013 / rowSums(table_fruits_form_2013)

# Calculate proportions for fruits in 2016
table_fruits_form_2016_prop <- table_fruits_form_2016 / rowSums(table_fruits_form_2016)

# Calculate proportions for fruits in 2020
table_fruits_form_2020_prop <- table_fruits_form_2020 / rowSums(table_fruits_form_2020)

# Calculate proportions for veggies in 2013
table_veggies_form_2013_prop <- table_veggies_form_2013 / rowSums(table_veggies_form_2013)

# Calculate proportions for veggies in 2016
table_veggies_form_2016_prop <- table_veggies_form_2016 / rowSums(table_veggies_form_2016)

# Calculate proportions for veggies in 2020
table_veggies_form_2020_prop <- table_veggies_form_2020 / rowSums(table_veggies_form_2020)
```






